version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço`
    build: . ## localização do dockerfile
    command: yarn dev ## comando a executar
    ports:
      - "${API_PORT}:${API_PORT}" ## redirecionamento de porta quando chegar alguma requisição na porta 80 chama o container na porta definia no .ENV
      - "9228:9228"
    volumes:
      - .:/home/app ## monitoro a pasta atual . e envio as alterações para /usr/app